### ISSUE TITLE
INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by keithOseis** [keithOseis/Translate#2]
TypeError [ERR_INVALID_ARG_TYPE]: The "args" argument must be of type object. Received type string ('undefined:undefined --br...)
    at new NodeError (node:internal/errors:278:15)
    at normalizeSpawnArguments (node:child_process:463:11)
    at spawn (node:child_process:615:13)
    at spawnWithSignal (node:child_process:755:17)
    at /code/routes/routes.js:13:12
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at next (/code/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at /code/node_modules/express/lib/router/index.js:281:22

**Comment by keithOseis** [comment]
Issue Solved
